=== dhermes/bezier/tests/functional/schema/curve_intersection.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "An intersection of two B\\u00e9zier curves.",
    "type": "object",
    "properties": {
        "curve1": {
            "description": "ID of the first curve in the intersection.",
            "type": "string"
        },
        "curve2": {
            "description": "ID of the second curve in the intersection.",
            "type": "string"
        },
        "id": {
            "description": "ID of intersection ``test case''.",
            "type": "integer"
        },
        "type": {
            "description": "Type of intersection that occurs.",
            "enum": [
                "no-intersection",
                "standard",
                "tangent",
                "coincident"
            ]
        },
        "note": {
            "description": "Description of the intersection / notes about how it behaves.",
            "type": "string"
        },
        "intersections": {
            "description": "A list of x-y coordinates where the curves intersect.",
            "type": "array",
            "items": {
                "description": "An x-y coordinate pair for a single intersection point.",
                "type": "array",
                "items": {
                    "description": "A coordinate as a numerical value.",
                    "$ref": "./numerical.json"
                }
            },
            "minItems": 2,
            "maxItems": 2
        },
        "curve1_params": {
            "description": "Parameters in curve 1 of the intersection points (in the same order).",
            "type": "array",
            "items": {
                "description": "A curve parameter as a numerical value.",
                "$ref": "./numerical.json"
            }
        },
        "curve1_polys": {
            "description": "The coefficients of the minimal polynomials that determine the values in ``curve1_params``. This can only be provided if both curves are defined by rational (or at least algebraic) control points.",
            "type": "array",
            "items": {
                "description": "The coefficients in a given polynomial, in order from lowest to highest exponent. For example, if a parameter is ``(7 - sqrt(7)) / 14`` (i.e. ``0x1.3e7b70cac040dp-2``) then the minimal polynomial is ``14 s^2 - 14 s + 3 = 0`` which is represented as ``[3, -14, 14]``.",
                "type": "array",
                "items": {
                    "description": "A coefficient in a polynomial.",
                    "type": "integer"
                },
                "minItems": 2
            }
        },
        "curve2_params": {
            "description": "Parameters in curve 2 of the intersection points (in the same order).",
            "type": "array",
            "items": {
                "description": "A curve parameter as a numerical value.",
                "$ref": "./numerical.json"
            }
        },
        "curve2_polys": {
            "description": "The coefficients of the minimal polynomials that determine the values in ``curve2_params``. This can only be provided if both curves are defined by rational (or at least algebraic) control points.",
            "type": "array",
            "items": {
                "description": "The coefficients in a given polynomial, in order from lowest to highest exponent. For example, if a parameter is ``cuberoot(1/4)`` (i.e. ``0x1.428a2f98d728bp-1``) then the minimal polynomial is ``4 s^3 - 1 = 0`` which is represented as ``[-1, 0, 0, 4]``.",
                "type": "array",
                "items": {
                    "description": "A coefficient in a polynomial.",
                    "type": "integer"
                },
                "minItems": 2
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "curve1",
        "curve2",
        "id",
        "type",
        "intersections",
        "curve1_params",
        "curve2_params"
    ]
}

=== dhermes/bezier/tests/functional/curve_intersections.json
[
    {
        "curve1": "1",
        "curve2": "2",
        "id": 1,
        "type": "standard",
        "intersections": [
            ["0x1.b7537f52e7c79p-3", "0x1.d22b202b460e2p-1"],
            ["0x1.59159015a3071p-2", "0x1.4dd4dfd4b9f1ep-3"]
        ],
        "curve1_params": [
            "0x1.b7537f52e7c79p-3",
            "0x1.d22b202b460e2p-1"
        ],
        "curve1_polys": [
            [25, -144, 128],
            [25, -144, 128]
        ],
        "curve2_params": [
            "0x1.d22b202b460e2p-1",
            "0x1.b7537f52e7c79p-3"
        ],
        "curve2_polys": [
            [25, -144, 128],
            [25, -144, 128]
        ]
    }, {
        "curve1": "3",
        "curve2": "4",
        "id": 2,
        "type": "standard",
        "intersections": [
            ["3/4", "21/8"],
            ["9/8", "21/32"]
        ],
        "curve1_params": [
            "1/4",
            "7/8"
        ],
        "curve2_params": [
            "3/4",
            "1/4"
        ]
    }, {
        "curve1": "1",
        "curve2": "5",
        "id": 3,
        "type": "standard",
        "intersections": [
            ["1/4", "3/4"],
            ["3/8", "3/8"]
        ],
        "curve1_params": [
            "1/4",
            "3/4"
        ],
        "curve2_params": [
            "1/4",
            "3/4"
        ]
    }, {
        "curve1": "1",
        "curve2": "6",
        "id": 4,
        "type": "tangent",
        "intersections": [
            ["1/2"],
            ["1/2"]
        ],
        "curve1_params": [
            "1/2"
        ],
        "curve2_params": [
            "1/2"
        ]
    }, {
        "curve1": "1",
        "curve2": "7",
        "id": 5,
        "type": "standard",
        "intersections": [
            ["0x1.36fa590b4b85dp-3", "0x1.b24169bd2d1e9p-1"],
            ["0x1.07c1f07c1f07cp-2", "0x1.07c1f07c1f07cp-2"]
        ],
        "curve1_params": [
            "0x1.36fa590b4b85dp-3",
            "0x1.b24169bd2d1e9p-1"
        ],
        "curve1_polys": [
            [17, -132, 132],
            [17, -132, 132]
        ],
        "curve2_params": [
            "0x1.36fa590b4b85dp-3",
            "0x1.b24169bd2d1e9p-1"
        ],
        "curve2_polys": [
            [17, -132, 132],
            [17, -132, 132]
        ]
    }, {
        "curve1": "1",
        "curve2": "8",
        "id": 6,
        "type": "standard",
        "intersections": [
            ["1/4", "3/4"],
            ["3/8", "3/8"]
        ],
        "curve1_params": [
            "1/4",
            "3/4"
        ],
        "curve2_params": [
            "1/4",
            "3/4"
        ]
    }, {
        "curve1": "1",
        "curve2": "9",
        "id": 7,
        "type": "standard",
        "intersections": [
            ["1/2"],
            ["1/2"]
        ],
        "curve1_params": [
            "1/2"
        ],
        "curve2_params": [
            "2/3"
        ]
    }, {
        "curve1": "10",
        "curve2": "11",
        "id": 8,
        "type": "standard",
        "intersections": [
            [3],
            [4]
        ],
        "curve1_params": [
            "1/3"
        ],
        "curve2_params": [
            "1/2"
        ]
    }, {
        "curve1": "8",
        "curve2": "9",
        "id": 9,
        "type": "standard",
        "intersections": [
            ["1/2"],
            ["3/8"]
        ],
        "curve1_params": [
            "1/2"
        ],
        "curve2_params": [
            "1/2"
        ]
    }, {
        "curve1": "1",
        "curve2": "13",
        "id": 10,
        "type": "standard",
        "intersections": [
            [0, "0x1.3e7b70cac040dp-2", "0x1.60c2479a9fdfap-1", 1],
            [0, "0x1.b6db6db6db6dbp-2", "0x1.b6db6db6db6dbp-2", 0]
        ],
        "curve1_params": [
            0,
            "0x1.3e7b70cac040dp-2",
            "0x1.60c2479a9fdfap-1",
            1
        ],
        "curve1_polys": [
            [0, 1],
            [3, -14, 14],
            [3, -14, 14],
            [-1, 1]
        ],
        "curve2_params": [
            0,
            "0x1.3e7b70cac040dp-2",
            "0x1.60c2479a9fdfap-1",
            1
        ],
        "curve2_polys": [
            [0, 1],
            [3, -14, 14],
            [3, -14, 14],
            [-1, 1]
        ]
    }, {
        "curve1": "14",
        "curve2": "15",
        "id": 11,
        "type": "tangent",
        "intersections": [
            ["1/2"],
            ["1/2"]
        ],
        "curve1_params": [
            "2/3"
        ],
        "curve2_params": [
            "1/3"
        ]
    }, {
        "curve1": "14",
        "curve2": "16",
        "id": 12,
        "type": "standard",
        "intersections": [
            ["3/8", "5/8"],
            ["15/32", "15/32"]
        ],
        "curve1_params": [
            "1/2",
            "5/6"
        ],
        "curve2_params": [
            "1/6",
            "1/2"
        ]
    }, {
        "curve1": "10",
        "curve2": "17",
        "id": 13,
        "type": "standard",
        "intersections": [
            [3],
            [4]
        ],
        "curve1_params": [
            "1/3"
        ],
        "curve2_params": [
            1
        ]
    }, {
        "curve1": "1",
        "curve2": "18",
        "id": 14,
        "type": "tangent",
        "intersections": [
            [1],
            [0]
        ],
        "curve1_params": [
            1
        ],
        "curve2_params": [
            0
        ]
    }, {
        "curve1": "1",
        "curve2": "19",
        "id": 15,
        "type": "standard",
        "intersections": [
            [1],
            [0]
        ],
        "curve1_params": [
            1
        ],
        "curve2_params": [
            1
        ]
    }, {
        "curve1": "1",
        "curve2": "20",
        "id": 16,
        "type": "standard",
        "intersections": [
            ["0x1.8722191a02d61p-4", "1/4", "0x1.4f1bbcdcbfa54p-1", 1],
            ["0x1.61c8864680b58p-3", "3/8", "0x1.cf1bbcdcbfa54p-2", 0]
        ],
        "curve1_params": [
            "0x1.8722191a02d61p-4",
            "1/4",
            "0x1.4f1bbcdcbfa54p-1",
            1
        ],
        "curve1_polys": [
            [1, -12, 16],
            [-1, 4],
            [1, -12, 16],
            [-1, 1]
        ],
        "curve2_params": [
            "0x1.61c8864680b58p-2",
            "3/4",
            "0x1.cf1bbcdcbfa54p-1",
            0
        ],
        "curve2_polys": [
            [5, -20, 16],
            [-3, 4],
            [5, -20, 16],
            [0, 1]
        ]
    }, {
        "curve1": "20",
        "curve2": "21",
        "id": 17,
        "type": "standard",
        "intersections": [
            [1, "0x1.8722191a02d61p-4", "1/4", "0x1.4f1bbcdcbfa54p-1"],
            [0, "0x1.61c8864680b58p-3", "3/8", "0x1.cf1bbcdcbfa54p-2"]
        ],
        "curve1_params": [
            0,
            "0x1.61c8864680b58p-2",
            "3/4",
            "0x1.cf1bbcdcbfa54p-1"
        ],
        "curve1_polys": [
            [0, 1],
            [5, -20, 16],
            [-3, 4],
            [5, -20, 16]
        ],
        "curve2_params": [
            "9/10",
            "0x1.6940d6d73455ap-3",
            "3/10",
            "0x1.3f4963e3cc843p-1"
        ],
        "curve2_polys": [
            [-9, 10],
            [11, -80, 100],
            [-3, 10],
            [11, -80, 100]
        ]
    }, {
        "curve1": "21",
        "curve2": "22",
        "id": 18,
        "type": "standard",
        "intersections": [
            ["0x1.8722191a02d61p-4", "1/4", "0x1.4f1bbcdcbfa54p-1", 1],
            ["0x1.61c8864680b58p-3", "3/8", "0x1.cf1bbcdcbfa54p-2", 0]
        ],
        "curve1_params": [
            "0x1.6940d6d73455ap-3",
            "3/10",
            "0x1.3f4963e3cc843p-1",
            "9/10"
        ],
        "curve1_polys": [
            [11, -80, 100],
            [-3, 10],
            [11, -80, 100],
            [-9, 10]
        ],
        "curve2_params": [
            "0x1.816d383866f7ap-2",
            "7/10",
            "0x1.a5afca4a32eaap-1",
            "1/10"
        ],
        "curve2_polys": [
            [31, -120, 100],
            [-7, 10],
            [31, -120, 100],
            [-1, 10]
        ]
    }, {
        "curve1": "10",
        "curve2": "23",
        "id": 19,
        "type": "tangent",
        "intersections": [
            ["9/2"],
            ["9/2"]
        ],
        "curve1_params": [
            "1/2"
        ],
        "curve2_params": [
            "3/10"
        ]
    }, {
        "curve1": "1",
        "curve2": "24",
        "id": 20,
        "type": "coincident",
        "note": "The curves in this intersection are coincident: curve1([1/4, 1]) == curve24([0, 3/4]).",
        "intersections": [
            ["1/4", 1],
            ["3/8", 0]
        ],
        "curve1_params": [
            "1/4",
            1
        ],
        "curve2_params": [
            0,
            "3/4"
        ]
    }, {
        "curve1": "15",
        "curve2": "25",
        "id": 21,
        "type": "standard",
        "intersections": [
            ["0x1.c9c6769baeb4bp-1"],
            ["0x1.9f09401c281dep-1"]
        ],
        "curve1_params": [
            "0x1.b7b348cf939b9p-1"
        ],
        "curve1_polys": [
            [1231, 6213, -18405, 13905, -3726, 486]
        ],
        "curve2_params": [
            "0x1.bf3536665a0cdp-1"
        ],
        "curve2_polys": [
            [4, -28, 25, 13, -16, 4]
        ]
    }, {
        "curve1": "11",
        "curve2": "26",
        "id": 22,
        "type": "standard",
        "intersections": [
            ["0x1.5eb412d9d98cep-1", 3, "0x1.54297da4c4ce6p+2"],
            ["0x1.c58ca7865bbdep+2", 4, "0x1.d39ac3cd22113p-1"]
        ],
        "curve1_params": [
            "0x1.d39ac3cd22113p-4",
            "1/2",
            "0x1.c58ca7865bbdep-1"
        ],
        "curve1_polys": [
