=== dhermes/bezier/tests/functional/schema/triangle_intersection.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "An intersection of two B\\u00e9zier surfaces.",
    "type": "object",
    "properties": {
        "surface1": {
            "description": "ID of the first surface in the intersection.",
            "type": "string"
        },
        "surface2": {
            "description": "ID of the second surface in the intersection.",
            "type": "string"
        },
        "id": {
            "description": "ID of intersection ``test case''.",
            "type": "integer"
        },
        "note": {
            "description": "Description of the intersection(s).",
            "type": "string"
        },
        "intersections": {
            "description": "List of info describing curved polygon(s) in the intersection.",
            "type": "array",
            "items": {
                "description": "Either a curved polygon that occurs within the surface-surface intersection or a boolean. If a boolean, `true` indicates that the intersection is the first surface (i.e. it's fully contained in the second) and `false` indicates that the intersection is the second surface.",
                "oneOf": [
                    {"type": "boolean"},
                    {"$ref": "./curved_polygon.json"}
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "surface1",
        "surface2",
        "id",
        "intersections"
    ]
}

=== dhermes/bezier/functional_tests/surface_intersections.json
[
    {
        "surface1": "1Q",
        "surface2": "3Q",
        "id": 1,
        "intersections": [
            {
                "nodes": [
                    [1, 0],
                    ["0x1.b3814fc520094p-2", "0x1.951b989d86b44p-1"],
                    ["0x1.e3902ffacd381p-4", "0x1.875633d1f12bep-2"],
                    [0, 0]
                ],
                "start_params": [
                    0,
                    "0x1.b05d9249bd0f1p-2",
                    "0x1.3c54e617076a1p-1",
                    0
                ],
                "start_param_polys": [
                    [0, 1],
                    [12, -28, 5, -18, 9],
                    [-244, 320, 91, 49],
                    [0, 1]
                ],
                "end_params": [
                    "0x1.5dad785d7b57dp-1",
                    "0x1.8b3631b4a4202p-1",
                    1,
                    1
                ],
                "end_param_polys": [
                    [-131, 200, 4, -48, 36],
                    [-128, 88, 63, 49],
                    [-1, 1],
                    [-1, 1]
                ],
                "edge_pairs": [
                    [0, 1],
                    [1, 2],
                    [0, 2],
                    [1, 0]
                ]
            }
        ]
    }, {
        "surface1": "1L",
        "surface2": "3L",
        "id": 2,
        "intersections": [
            {
                "nodes": [
                    ["1/4", 0],
                    [1, 0],
                    ["1/4", "3/4"]
                ],
                "start_params": [
                    "1/4",
                    0,
                    "1/8"
                ],
                "end_params": [
                    1,
                    "3/4",
                    "7/8"
                ],
                "edge_pairs": [
                    [0, 0],
                    [0, 1],
                    [1, 2]
                ]
            }
        ]
    }, {
        "surface1": "1Q",
        "surface2": "2Q",
        "id": 3,
        "intersections": [
            {
                "nodes": [
                    ["0x1.0720ad954785ap-1", "-0x1.ff9a64abf6237p-4"],
                    ["0x1.9b36174dc0245p-1", "-0x1.43cae8b404cfdp-4"],
                    ["0x1.ae14d9f3b87dap-1", "0x1.665c7eaaac924p-2"],
                    ["0x1.665c7eaaac924p-2", "0x1.ae14d9f3b87dap-1"],
                    ["0x1.1ecd1d985d392p-4", "0x1.a9c7d37bb78c1p-1"],
                    ["0x1.68a193f04e2b7p-4", "0x1.d33874bafeb64p-3"]
                ],
                "start_params": [
                    "0x1.0720ad954785ap-1",
                    "0x1.5e1a8ba5fd981p-3",
                    "0x1.051965619dcb8p-2",
                    "0x1.99a38155536dcp-2",
                    "0x1.58e0b21121cfep-3",
                    "0x1.b846154f4a17ep-2"
                ],
                "start_param_polys": [
                    [10, -21, 3],
                    [20, -116, -3, -18, 9],
                    [23, -100, 56, -72, 12],
                    [64, -160, 25, -66, 9],
                    [23, -140, 24, -24, 12],
                    [-44, 36, 181, -66, 9]
                ],
                "end_params": [
                    "0x1.9b36174dc0245p-1",
                    "0x1.332e3f5556492p-1",
                    "0x1.7d734d4f311a4p-1",
                    "0x1.5c265c4cf458ep-1",
                    "0x1.8b31e2d140527p-1",
                    "0x1.a389fd1563251p-1"
                ],
                "end_param_polys": [
                    [-105, 140, 0, -24, 12],
                    [-128, 272, -119, 30, 9],
                    [-81, 156, -88, 24, 12],
                    [84, -116, -3, -18, 9],
                    [-96, -12, 213, -54, 9],
                    [-38, 39, 9]
                ],
                "edge_pairs": [
                    [0, 0],
                    [1, 1],
                    [0, 1],
                    [1, 2],
                    [0, 2],
                    [1, 0]
                ]
            }
        ]
    }, {
        "surface1": "10Q",
        "surface2": "18Q",
        "id": 4,
        "intersections": [
            {
                "nodes": [
                    ["1/2", "-3/4"],
                    ["3/4", "3/32"],
                    [0, 0]
                ],
                "start_params": [
                    0,
                    "1/4",
                    0
                ],
                "end_params": [
                    1,
                    1,
                    1
                ],
                "edge_pairs": [
                    [1, 2],
                    [0, 0],
                    [0, 1]
                ]
            }
        ]
    }, {
        "surface1": "10Q",
        "surface2": "19Q",
        "id": 5,
        "note": "These surfaces do not intersect. However, they share an entire edge (edge 1 of 10Q and edge 2 of 19Q).",
        "intersections": []
    }, {
        "surface1": "3Q",
        "surface2": "4Q",
        "id": 6,
        "intersections": [
            {
                "nodes": [
                    ["0x1.a60d77b0f5461p-2", "0x1.8fb5c4ada7847p-1"],
                    ["0x1.d5f30c47e44bbp-5", "0x1.c8a052e8c3322p-3"],
                    [1, "1/4"]
                ],
                "start_params": [
                    "0x1.bcb600f2baa8cp-2",
                    "0x1.d5f30c47e44bbp-5",
                    0
                ],
                "start_param_polys": [
                    [-468, 1008, 145, 14, 49],
                    [169, -2988, 712, 360, 100],
                    [0, 1]
                ],
                "end_params": [
                    "0x1.bf4d1aea77580p-1",
                    1,
                    "0x1.6a47b0e78a05ep-1"
                ],
                "end_param_polys": [
                    [-96, -88, 321, -130, 25],
                    [-1, 1],
                    [-26352, 37200, 412, -532, 49]
                ],
                "edge_pairs": [
                    [0, 2],
                    [1, 0],
                    [1, 1]
                ]
            }
        ]
    }, {
        "surface1": "1Q",
        "surface2": "5L",
        "id": 7,
        "intersections": [
            {
                "nodes": [
                    ["1/8", "1/2"],
                    [0, 0],
                    [1, 0],
                    ["0x1.78dde6e5fd29fp-1", "1/2"]
                ],
                "start_params": [
                    "1/2",
                    0,
                    0,
                    "0x1.d1f49bd925a6ep-2"
                ],
                "start_param_polys": [
                    [-1, 2],
                    [0, 1],
                    [0, 1],
                    [1049, -3108, 1764]
                ],
                "end_params": [
                    1,
                    1,
                    "0x1.8722191a02d61p-2",
                    "4/7"
                ],
                "end_param_polys": [
                    [-1, 1],
                    [-1, 1],
                    [1, -3, 1],
                    [-4, 7]
                ],
                "edge_pairs": [
                    [0, 2],
                    [0, 0],
                    [0, 1],
                    [1, 1]
                ]
            }
        ]
    }, {
        "surface1": "3Q",
        "surface2": "5Q",
        "id": 8,
        "intersections": [
            {
                "nodes": [
                    ["0x1.5ffbf1646a43ep-1", "0x1.df044f8131ab6p-1"],
                    ["0x1.295cb92910465p-1", "0x1.c7a0bfd320f74p-1"],
                    ["1/4", "3/32"],
                    ["9/8", "3/8"]
                ],
                "start_params": [
                    "0x1.ac579d93b5440p-3",
                    "0x1.e2f091e94f79dp-4",
                    0,
                    0
                ],
                "start_param_polys": [
                    [57, -302, 167, -130, 25],
                    [11664, -105840, 58908, -2340, 25],
                    [0, 1],
                    [0, 1]
                ],
                "end_params": [
                    "0x1.296332cad18aap-2",
                    1,
                    1,
                    "0x1.c0081d372b785p-1"
                ],
                "end_param_polys": [
                    [279, -1212, 901, -130, 25],
                    [-1, 1],
                    [-1, 1],
                    [-6012, 7800, -1064, -20, 25]
                ],
                "edge_pairs": [
                    [0, 2],
                    [1, 2],
                    [1, 0],
                    [1, 1]
                ]
            }
        ]
    }, {
        "surface1": "1L",
        "surface2": "2L",
        "id": 9,
        "intersections": [
            {
                "nodes": [
                    ["2/3", "1/3"],
                    ["9/16", "7/16"],
                    ["1/8", "3/8"],
                    [0, "5/32"],
                    [0, 0]
                ],
                "start_params": [
                    "1/3",
                    "1/2",
                    0,
                    "27/32",
                    "1/9"
                ],
                "end_params": [
                    "7/16",
                    1,
                    "1/2",
                    1,
                    "19/27"
                ],
                "edge_pairs": [
                    [0, 1],
                    [1, 1],
                    [1, 2],
                    [0, 2],
                    [1, 0]
                ]
            }
        ]
    }, {
        "surface1": "20Q",
        "surface2": "21Q",
        "id": 10,
        "intersections": [
            {
                "nodes": [
                    [1, 0],
                    [0, 1],
                    ["-1/2", "1/2"],
                    ["-1/2", "1/4"]
                ],
                "start_params": [
                    0,
                    0,
